notify = true
hide_display_names = true

[track_format]
left = "%artists %title"
center = "%album"
right = "%saved %duration"

[theme]
background = "#303446"
primary = "#c6d0f5"
secondary = "#81c8be"
title = "#8caaee"
playing = "#a6d189"
playing_bg = "#303446"
highlight = "#c6d0f5"
highlight_bg = "#5e6f9a"
playing_selected = "#a6d189"
error = "#303446"
error_bg = "#e78284"
statusbar = "#8caaee"
statusbar_bg = "#414559"
statusbar_progress = "#8caaee"
cmdline = "#8caaee"
cmdline_bg = "#292c3c"
